In [1]:
import numpy as np

In [2]:
narr = np.array([1,2,3,4,5])
narr

array([1, 2, 3, 4, 5])

In [3]:
arr = [1,2,3,4,5]
narr = np.array(arr)
narr

array([1, 2, 3, 4, 5])

In [4]:
arr = [1,2,3,4,5]
narr = np.asarray(arr)
narr

array([1, 2, 3, 4, 5])

In [5]:
narr = np.arange(0, 100, 2)
narr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [6]:
narr = np.zeros(10)
narr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
narr = np.ones(10)
narr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
narr = np.zeros(8).reshape((2,2,2))
narr

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
# Creating a linearly spaced vector
vector = np.linspace(0, 20, 5)
print(vector)

[ 0.  5. 10. 15. 20.]


In [10]:
narr = np.zeros(8).reshape((2,2,2))
narr = narr.ravel()
narr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
narr = np.zeros(8).reshape((2,2,2))
narr = narr.flatten()
narr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
narr = np.arange(10)
narr[5]

np.int64(5)

In [13]:
narr = np.arange(10)
narr_slice = slice(0, 5, 2)
narr[narr_slice]

array([0, 2, 4])

In [14]:
narr = np.arange(10)
narr[5:]

array([5, 6, 7, 8, 9])

In [15]:
narr_slice = slice(0, 5, 2)
narr[:5]

array([0, 1, 2, 3, 4])

In [16]:
narr = np.arange(8).reshape(2,2,2)
print(narr)
print()
print(narr[0:2, 0:1, 1:2])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[1]]

 [[5]]]


In [17]:
narr = np.empty((2, 3, 4), dtype=int)
narr

array([[[           181695198,                    0,
             2533313445691401,    48138287078209892],
        [ 6294343429203689473,   325488858720655461,
                        65707,  7450079723228846426],
        [    2533313445691401,   397547552286965769,
                        65707,  6945794603549547098]],

       [[          4306175108,  7450079723764973568,
          7522137316270866441,  7450181225287016804],
        [ 6726695059575831652,  6798751554118904676,
           397553049895468388,   325496555050393434],
        [ 9179575621081456730,      282209508681316,
            38387636007600128, -4223250192434331272]]])

In [18]:
narr = np.arange(8).reshape(2,2,2)

print(narr.dtype)
print(narr.itemsize)
print(narr.ndim)
print(narr.shape)


int64
8
3
(2, 2, 2)
